### ISSUE TITLE
Problem with EthereumProvider configuration file

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [oeg-upm/helio-plugins#12]
The current file has a wrong value for the "source", the plugin configuration file that works is this one:
{
	"plugins" : [
		{ 
			"type" : "DataProvider", 
			"class":"helio.materialiser.data.providers.EthereumDataProvider", 
			"source":"https://github.com/oeg-upm/helio-plugins/releases/download/1.0.0/EthereumDataProvider.jar"
		}
	]
}

**Comment by juancanobenito** [comment]
Solved
